global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-service:3000']
  - job_name: 'python-app'
    static_configs:
      - targets: ['python-service:5000']
  - job_name: 'go-app'
    static_configs:
      - targets: ['go-service:8080']
