{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /node
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              number: {{ .Values.node.servicePort }}
      - path: /python
        pathType: Prefix
        backend:
          service:
            name: python-service
            port:
              number: {{ .Values.python.servicePort }}
      - path: /go
        pathType: Prefix
        backend:
          service:
            name: go-service
            port:
              number: {{ .Values.go.servicePort }}
{{- end }}
