version: '3.9'

services:

    app1:
       build: ./app1
       container_name: app1
       ports:
         - "5000:5000"

    app2:
       build: ./app2
       container_name: app2
       ports:
         - "5001:5001"     

    nginx:
       image: nginx:latest
       container_name: nginx-lb
       volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          
       ports:
          -  "8080:80"
       depends_on:
          - app1
          - app2 