version: '3.9'

services:
  app:
    build: ./node-app
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--bind_ip_all"]

volumes:
  mongo_data:
