apiVersion: v1
kind: Config

clusters:
- name: fake-cluster
  cluster:
    server: https://127.0.0.1:6443   # fake unreachable cluster

contexts:
- name: fake-context
  context:
    cluster: fake-cluster
    user: fake-user

current-context: fake-context

users:
- name: fake-user
  user:
    token: "dummy"
